### ISSUE TITLE
Level3 Issues

### ISSUE THREAD

**Issue by mdc2684** [mdc2684/HH99firstSpringLevel3#2]
1. 
Board board = boardRepository.findById(id).orElseThrow(()-> new CustomException(BOARD_NOT_FOUND));

findById()는 Optional인데 orElse하면 왜 board로 저장가능하게 되는지 궁금합니다.

2. CommentService의
Comment comment = commentRepository.save(new Comment(commentRequestDto, user, board));
        return new CommentResponseDto(comment);
이 부분에서
댓글은 content만 반환하면되는데 어째서 user객체와 board객체도 매개변수로 받아서 생성하는지 이해가 안 갑니다.
단지 Comment Entity가  User객체와 Board객체를 포함해서 그런이유인가요?

3. SignUpRequestDto에서 유효성검사처리를 해주었는데 잘못된 입력을 Postman에서 실험해보니,
  어떠한 메세지도 반환을 해주지 않습니다. 이유가 무엇일까요

**Comment by paran22** [comment]
1. findById는 orElseThrow로 처리하셔도 되고 Optional로 처리하셔도 됩니다! Optional로 처리하면 Board가 아니라 Optional<Board>로 리턴이 되겠죠?
2. Comment Entity에 user와 board를 저장해주기 위해서입니다. Comment에 연관관계를 맺어놓은 이유는 Comment를 작성한 User와 Comment가 달린 Board 정보를 같이 저장하기 위해서이고, 따라서 Comment를 만들 때 해당하는 user와 board를 같이 저장해주는 걸로 이해하시면 될 것 같아요.
3. 현재 유효성 검사를 @Pattern 어노테이션을 사용하고 있는데요. `@ExceptionHandler(CustomException.class)`에서 CustomException만 처리를 하고 있어서 그런 것 같아요. @Pattern에서 어떤 Exception이 던져지는지 확인해서 처리를 하셔도 좋을 것 같고, 아니면 @Patter이 아니라 다른 방법으로 유효성 검사를 하면서 CustomException을 던져도 될 것 같아요.

**Comment by paran22** [comment]
```
@PostMapping("/signup")
    public ResponseEntity<MsgResponseDto> signup(@Valid @RequestBody SignupRequestDto signupRequestDto) {
        userService.signUp(signupRequestDto); //ResponseEntity: 결과값, 상태코드, 헤더값을 모두 프론트에 넘겨줄 수 있고, 에러코드 또한 섬세하게 설정해서 보내줄 수 있음
        return ResponseEntity.ok(new MsgResponseDto("회원가입완료", HttpStatus.OK.value()));
    }
```
Service로직은 void이기 때문에, 에러가 던져지지 않았다면 controller로 돌아와서 return이 될거에요. 그렇지만 이 api에 주요 로직은 service에서 처리하고 있고, service 로직의 결과로(이 경우에는 성공적으로 회원가입을 한 경우)  `ResponseEntity.ok(new MsgResponseDto("회원가입완료", HttpStatus.OK.value()));`을 리턴하는 것이기 때문에 Service에서 return을 하는게 좋을 것 같아요.
또, api가 반드시 값을 리턴할 필요는 없습니다. 아에 아무것도 리턴하지 않아도 괜찮아요.

**Comment by paran22** [comment]
```
 public User checkToken(HttpServletRequest request) {
        // Request에서 Token 가져오기
        String token = jwtUtil.resolveToken(request); // request 토큰값 찾기
        Claims claims;

        // 토큰이 있는경우에만 댓글작성 가능
        if (token != null) {
            if (jwtUtil.validateToken(token)) {  // 토큰 유효 검사
                claims = jwtUtil.getUserInfoFromToken(token);   //토큰에서 사용자 정보 가져오기
            } else {
                throw new CustomException(INVALID_AUTH_TOKEN);
            }
            User user = userRepository.findUserByUsername(claims.getSubject())
                    .orElseThrow(  () -> new CustomException(UNAUTHORIZED_USER));

            return user;
        }
        return null;
    }
```
토큰이 null이라면 null을 return하고 있는데, 이후에 이 null을 처리하는 로직이 없습니다. 토큰이 없다면 정상적으로 인증이 되지 않은 것이므로 에러를 던지는게 좋을 것 같아요.

또, BoardService와 CommentService에 `checkToken`이 동일합니다. 같은 메서드라면 한쪽에 관리를 하는게 이후에 수정하기에도 좋아요.

**Comment by mdc2684** [comment]
Entity Board에서
@Column
@ColumnDefault("0")
private int liked;


private long lied;로 했었는데 계속 null로 나왔습니다. 시간을 굉장히 오래쓰고 int로 바꾸니까 되던데 이 이유가 궁금합니다
